# before committing check this file here: https://lint.travis-ci.org/

language: python

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.6
    env: TOXENV=coverage
#  - python: 3.2
#    env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0" STVER="<30.0.0"
#    dist: trusty
#  - python: 3.4
#    env: TOXENV=py34
#    dist: trusty
#  - python: 3.5
#    env: TOXENV=py35
#  - python: 3.6
#    env: TOXENV=py36
#  - python: 3.7
#    env: TOXENV=py37
#    sudo: true
#  - python: 3.4
#    env: TOXENV=docs
#  - python: 2.7
#    env: TOXENV=pep8
#  - python: 3.6
#    env: TOXENV=pep8
#  - python: 3.6
#    env: TOXENV=packaging
#  allow_failures:
#  - python: 3.2
#    env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0" STVER="<30.0.0"
#    dist: trusty

# travis-ci runs by default on ancient Ubuntu 12.04 (precise)
# following options will give us Ubuntu 14.04 (trusty) x
sudo: false
dist: xenial

install:
- ./.travis/install_linux.sh

script:
- tox --notest && travis_retry tox --
- if [[ "$TRAVIS_TEST_RESULT" == "0" ]] && [[ $TOXENV == "packaging" ]]; then .travis/deploy_package.sh ; fi


# automatic deploy to github releases and pypi    
deploy:
  - provider: releases
    api_key:
      secure: vobq0zAt/xwn3qjqLMyqGiNCEYSg6Xah83ohK93UmIsMZtASQwLgioCDaqE1Lkmu5SwAYSUgyydo3JieEhFTImEx+9+tbwDPNNukosKMiMB6xzN7mCIRlYWL/FiMBvRQt4D8kxXjwUynvY/kDan9V+KIvCwH1+M3mMA96naYpwhn4xKn2PKxTR0wvecZw/hyZs+EucmeqyjmNr5ctFqTfIEVQee0u7aejJ4NXRlbNKrrLOw0eqjISJba3Ggr2JTnVK8H1d3yDIT/4iqUv01fzZTm6V+PgdGAAVtozpO83oun8qCN9Perme3xx0qpNl+qh18b7d/biRYDkti5fQVfzY8ocMAXgTh4fiSuOa9tumhAkZBVAW45eDTmYXZ6PZFFSFBpmR4S1J77kt+4EwrCky0hlNOZ89mIXqtE17X9r5f+pu6NI2re0MZo0oB8YeAKHb8/qxgAHdIFM9B4lxwteQ1sEI3R5HsLGOjB0QmiP9igu52lcJVGMnFXeSua7VmDYX+EHtK8fUkJnHPs9xaQ8jSMTYPdVP2znbp41MZH8bOC1Qm63XxPX/6dmSyThk03vfqFJ7sXOCiGuxhg8y9P9J0Z6BSXjBAHwP1SagT9ZJQV26+m3kJbOaNlpv+1OuLQ7XRb68OyEaD6EMDD8NjyQRy6YJGMy5mTPAv1n4QieJ8=
    file: "./release_files/*"
    file_glob: true
    overwrite: true
    skip_cleanup: true
    on:
      repo: DataMedSci/mcpartools
      tags: true
      condition: $TOXENV == "packaging" && "$TRAVIS_TEST_RESULT" == "0"
  - provider: pypi
    user: grzanka
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    password:
      secure: bjHbQLyCSLiT8mqN4yYDBoV6eNvUAF+Ki+yJ5uc2zgqkqmG5BPRIbp8mr902OYbFEZou/+9qeoelHeU3Kjg4oYQ/BvAZgV8sUfhNVcpMc/QKvCyP7MdS+HZhXRy17zRMh9cY0esRk+CJe119nkB9mzPTbv7YgE8jHzCP8N19hwsIrS9fhJkkrsTAsAWdchlyPG4qVELR4AwJhUA0nzvg85M5oY7162fPxxSJg2a21bdbCbNHmuVNwwCOZLMnaie7CuLr1MCMvGGcheVukP/JhtuSx+Fy6SjBvmWLymalDGsf3O98VNeQweWvqmc2IWtGQ6eaRvEIEwrUa7jxiKlYLBellJhkA/1EBu/yKBHy5XMINWHzmfsRzWwC2xa08iU8dAq0fLpKms0P0Htii/AJctaVn+p/GTxzSjr2bOTXJiRpnO0jIexxQ9za0cOwX7EgE/psU0Uwb/LzIxdPv8LHinPiq3GVQdmRK1G/sMrRI31OTqVM6byEkL0F6D5U77CJtmtVyfcaBQCCxt8/kE/B0nw3Sbf3dSKtcTQ98073V2ElSTXc5vytTleNJaj5qY5NpQAdlrJyo/G2+GDZj/8dm4ghMdF/DEg+3lJXMLbal9rRQIfLIo1sGBDx+Gqd7Iwg1Sg0uXutyf/tUkrpUxUcqUXpf/U6u8jJEy1yWXhm+ZU=
    on:
      repo: DataMedSci/mcpartools
      tags: true
      condition: $TOXENV == "packaging" && "$TRAVIS_TEST_RESULT" == "0"
