name: Build and Deploy Docs (Multi-version)

on:
  push:
    branches:
      - master
      - docs-develop # Uruchamia dla zmian na gałęzi dokumentacji
    tags:
      - 'v*.*.*'

  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install documentation dependencies
      run: |
        python -m pip install --upgrade setuptools
        pip install ".[docs]"

    - name: Build multi-version documentation
      run: |
        sphinx-multiversion docs _build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        force_orphan: true