name: Pull Request Automation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR Best Practices
        id: check_pr_description_and_issues
        run: |
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_URL="${{ github.event.pull_request.html_url }}"

          if [ -z "$PR_DESCRIPTION" ] || [ "$PR_DESCRIPTION" == "null" ]; then
            echo "::warning file=.github/workflows/pr-automation.yml::Pull Request description is empty. Please provide a description for the pull request."
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"body":"@${{ github.actor }} please provide a description for this pull request."}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          fi
        shell: bash

      - name: Label PR by Size
        uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label PR by Type
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true