name: Welcome a first-time contributor

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

jobs:
  welcome-first-time-contributor:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: plbstl/first-contribution@v3
        with:
          labels: first contrib
          issue-opened-msg: |
            ### Hey @{fc-author} !

            Looks like it's your first time interacting with (mcpartools) here on GitHub.

            Welcome and thank you for taking the time to report an issue :heart:.

            Please check out our [code of conduct](https://github.com/DataMedSci/mcpartools/blob/master/CODE_OF_CONDUCT.md) to learn how to interact with the community.

            Don't forget to star :star: the repo.
          pr-opened-msg: |
            ### Hey @{fc-author} !

            Thank you for taking the time to contribute to (Project Name). Your help is truly appreciated :heart:.

            Please check out our [code of conduct](https://github.com/DataMedSci/mcpartools/blob/master/CODE_OF_CONDUCT.md) to learn how to interact with the community.

            Please check out the [contribution guide](https://mcpartools.readthedocs.io/en/stable/contributing.html) which is very useful for working with the project.

            Don't forget to star :star: the repo.